package com.demo.bean;

import java.io.Serializable;
import java.util.Date;

public class UserBinding implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_binding.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_binding.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_binding.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_binding.photo
     *
     * @mbggenerated
     */
    private String photo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_binding.comment
     *
     * @mbggenerated
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_binding.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_binding.binding_type
     *
     * @mbggenerated
     */
    private Integer bindingType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_binding.effective
     *
     * @mbggenerated
     */
    private Boolean effective;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_binding.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_binding.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_binding
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    public UserBinding(Integer id, Integer userId, String name, String photo, String comment, String code, Integer bindingType, Boolean effective, Date createTime, Date updateTime) {
        this.id = id;
        this.userId = userId;
        this.name = name;
        this.photo = photo;
        this.comment = comment;
        this.code = code;
        this.bindingType = bindingType;
        this.effective = effective;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    public UserBinding() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_binding.id
     *
     * @return the value of user_binding.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_binding.id
     *
     * @param id the value for user_binding.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_binding.user_id
     *
     * @return the value of user_binding.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_binding.user_id
     *
     * @param userId the value for user_binding.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_binding.name
     *
     * @return the value of user_binding.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_binding.name
     *
     * @param name the value for user_binding.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_binding.photo
     *
     * @return the value of user_binding.photo
     *
     * @mbggenerated
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_binding.photo
     *
     * @param photo the value for user_binding.photo
     *
     * @mbggenerated
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_binding.comment
     *
     * @return the value of user_binding.comment
     *
     * @mbggenerated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_binding.comment
     *
     * @param comment the value for user_binding.comment
     *
     * @mbggenerated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_binding.code
     *
     * @return the value of user_binding.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_binding.code
     *
     * @param code the value for user_binding.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_binding.binding_type
     *
     * @return the value of user_binding.binding_type
     *
     * @mbggenerated
     */
    public Integer getBindingType() {
        return bindingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_binding.binding_type
     *
     * @param bindingType the value for user_binding.binding_type
     *
     * @mbggenerated
     */
    public void setBindingType(Integer bindingType) {
        this.bindingType = bindingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_binding.effective
     *
     * @return the value of user_binding.effective
     *
     * @mbggenerated
     */
    public Boolean getEffective() {
        return effective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_binding.effective
     *
     * @param effective the value for user_binding.effective
     *
     * @mbggenerated
     */
    public void setEffective(Boolean effective) {
        this.effective = effective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_binding.create_time
     *
     * @return the value of user_binding.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_binding.create_time
     *
     * @param createTime the value for user_binding.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_binding.update_time
     *
     * @return the value of user_binding.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_binding.update_time
     *
     * @param updateTime the value for user_binding.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}